currency:
  api-url: "http://www.cbr.ru/scripts/XML_daily.asp"

spring:
  cache:
    type: simple
  application:
    name: currency-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/homework_10
    username: postgres
    password: 4096
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
        ddl-auto: update
    show-sql: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

app:
  pool:
    size:
      thread: 3
      scheduler: 2
  initialization:
    schedule-delay: PT1M

command:
  api-url:
    categories: "https://kudago.com/public-api/v1.4/place-categories"
    locations: "https://kudago.com/public-api/v1.4/locations"

jwt:
  secret: 30faa058f27f690c7e9a098d54ebcfb3d8725bcb85ee7907a2d84c69622229e2
