name: CI Pipeline
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 4096
          POSTGRES_DB: homework_10
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --entrypoint redis-server

      wiremock:
        image: wiremock/wiremock:latest
        ports:
          - 8080:8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and Test
        run: |
          mvn clean verify

      - name: Run Tests and Generate Coverage Report
        run: |
          mvn test jacoco:report
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test-db
          SPRING_PROFILES_ACTIVE: test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco

      - name: Check Test Coverage
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: target/site/jacoco/jacoco.csv

      - name: Run Static Code Analysis (SonarQube)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn sonar:sonar -Dsonar.projectKey=TancorDisco_Homework -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=tancordisco

      - name: Build Docker Image
        run: |
          docker build -t homework:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GitHub Packages
        run: |
          docker homework:latest ghcr.io/${{ github.repository }}/homework:latest
          docker push ghcr.io/${{ github.repository }}/homework:latest